#include <cpp3ds/Config.hpp>
#include <map>

namespace cpp3ds {
    namespace priv {

        struct ResourceInfo {
            ResourceInfo() : data(nullptr), size(0) { }
            ResourceInfo(const Uint8 *x, const Uint32 y) : data(x), size(y) { }
            const Uint8 *data;
            const Uint32 size;
        };

        // Defined by source file generated by res_compile.py
		extern std::map<std::string, ResourceInfo> core_resources;

    } // namespace priv
} // namespace cpp3ds